{
 "title": "Docker Metrics for Raspberry Pi",
 "description": "Dashboard with details of the container and host OS metrics for Raspberry Pi by Oijkn.",
 "tags": [
  "prometheus",
  "cAdvisor",
  "node-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup-pi",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  { "title": "Debian", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 8, "y": 1 } },
  { "title": "Homeassistant", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 16, "y": 1 } },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "description": "Hardware temperature",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "description": "Hardware temperature",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\", instance=\"node-exporter:9100\", job=\"node-exporter\", sensor=\"temp1\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\" or r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"memory_use_percent\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"System Monitor Memory usage\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "description": "Hardware temperature",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GiB\" or r[\"_measurement\"] == \"°C\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"System Monitor Processor temperature\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\", instance=\"node-exporter:9100\", job=\"node-exporter\", sensor=\"temp1\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GiB\" or r[\"_measurement\"] == \"°C\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"System Monitor Processor temperature\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\" or r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"memory_use_percent\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"System Monitor Memory usage\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> yield(name: \"median\")"
    }
   ]
  }
 ]
}