services:
  heimdall:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "heimdall"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$"
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"

    hostname: "a7cd6ff66500"

    image: "linuxserver/heimdall:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v2.6.1-ls269 Build-date:- 2024-06-14T18:34:51+00:00"
      maintainer: "aptalca"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2024-06-14T18:34:51+00:00"
      org.opencontainers.image.description: "[Heimdall](https://heimdall.site) is a way to organise all\
        \ those links to your most used web sites and web applications in a simple way.    Simplicity\
        \ is the key to Heimdall.    Why not use it as your browser start page? It even has the ability\
        \ to include a search bar using either Google, Bing or DuckDuckGo.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-heimdall"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "438ca48450fcca621e62714c98e2e7d7bef305e5"
      org.opencontainers.image.revision: "438ca48450fcca621e62714c98e2e7d7bef305e5"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-heimdall"
      org.opencontainers.image.title: "Heimdall"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-heimdall/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v2.6.1-ls269"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "02:42:ac:11:00:04"

    network_mode: "bridge"

    ports:
      - "7203:443/tcp"
      - "7202:80/tcp"

    restart: "unless-stopped"

    volumes:
      - "/home/surya/NAS_STORAGE/heimdall:/config"

    working_dir: "/"

version: "3.6"