version: "3"

services:
  openbudgeteer:
    image: axelander/openbudgeteer:latest
    #image: axelander/openbudgeteer:pre-release
    #image: axelander/openbudgeteer:1.7
    container_name: openbudgeteer
    ports:
      - 8097:8080
    environment:
      - CONNECTION_PROVIDER=SQLITE
      - CONNECTION_DATABASE=/srv/openbudgeteer.db
    volumes:
      - /home/ubuntu/openbudget/data:/srv