version: '3.0'

services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Asia/Kolkata'
    # Volumes store your data between container upgrades
    volumes:
      - '/home/ubuntu/wallos/db:/var/www/html/db'
      - '/home/ubuntu/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped